### ISSUE TITLE
File Upload Issue

### ISSUE THREAD

**Issue by morganksmall** [nasa/puma#11]
Hello! I am having trouble uploading a .tif file into puma. I am trying to use the ones on github (python/pumapy/data) but it isn't working. I've checked to make sure it is an 8-bit .tif file as specified in the youtube tutorial, but I haven't had any success. How do I resolve this issue?

Thank you!

-Morgan

**Comment by fsemerar** [comment]
Hi, we need some more information about the exact commands you are trying. What OS are you trying on? Are you trying import the tifs into pumapy or the pumaGUI or the PuMA cpp library?
