### ISSUE TITLE
Oxidation in V3.0

### ISSUE THREAD

**Issue by jazorn** [nasa/puma#12]
I don't see a separate discussions tab for this project, so I will just post as an issue. 

Does V3.0 of PuMA have the oxidation feature that V2.0 had (at least seemed to have from the youtube tutorials)?

**Comment by fsemerar** [comment]
The oxidation module is not released in the open-source version 3, but you can still get access to it by requesting access to PuMA v2 contacting the [NASA software catalog](https://software.nasa.gov/software/ARC-17920-1A)
