### ISSUE TITLE
Installation issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by bilenemek** [nasa/puma#14]
Dear All

I am building from scratch and after compiling, by installing, I receive this error and it stops. Any idea what to change?

Starting pumapy installation.

Processing /home/prog/puma
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      /tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/prog/puma/python/pumapy/generation/tpms_utils.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/prog/puma/python/pumapy/physics_models/finite_volume/anisotropic_conductivity_utils.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/prog/puma/python/pumapy/physics_models/finite_volume/elasticity_utils.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          for i in range(len_x + 2):
              for j in range(len_y + 2):
                  for k in range(len_z + 2):
                      if i == 0 or i == len_x + 1 or j == 0 or j == len_y + 1 or k == 0 or k == len_z + 1:
                          ws_pad[i, j, k] = ws_pad[index_at_pad(i, len_x + 1),
                                                  ^
      ------------------------------------------------------------
      
      python/pumapy/physics_models/finite_volume/elasticity_utils.pyx:38:44: Compiler crash in AnalyseExpressionsTransform
      
      ModuleNode.body = StatListNode(elasticity_utils.pyx:1:0)
      StatListNode.stats[7] = StatListNode(elasticity_utils.pyx:25:0)
      StatListNode.stats[0] = DefNode(elasticity_utils.pyx:25:0,
          is_cyfunction = True,
          modifiers = [...]/0,
          name = 'pad_domain_cy',
          np_args_idx = [...]/0,
          num_required_args = 7,
          outer_attrs = [...]/2,
          py_wrapper_required = True,
          reqd_kw_flags_cname = '0',
          used = True)
      File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:27:4)
      File 'Nodes.py', line 7556, in analyse_expressions: ForInStatNode(elasticity_utils.pyx:34:4)
      File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:35:8)
      File 'Nodes.py', line 7556, in analyse_expressions: ForInStatNode(elasticity_utils.pyx:35:8)
      File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:36:12)
      File 'Nodes.py', line 7556, in analyse_expressions: ForInStatNode(elasticity_utils.pyx:36:12)
      File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:37:16)
      File 'Nodes.py', line 7137, in analyse_expressions: IfStatNode(elasticity_utils.pyx:37:16)
      File 'Nodes.py', line 7184, in analyse_expressions: IfClauseNode(elasticity_utils.pyx:37:19)
      File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:38:44)
      File 'Nodes.py', line 6026, in analyse_expressions: SingleAssignmentNode(elasticity_utils.pyx:38:44)
      File 'Nodes.py', line 6158, in analyse_types: SingleAssignmentNode(elasticity_utils.pyx:38:44)
      File 'ExprNodes.py', line 4082, in analyse_types: IndexNode(elasticity_utils.pyx:38:44,
          is_subscript = True,
          result_is_used = True,
          use_managed_ref = True)
      File 'ExprNodes.py', line 4123, in analyse_base_and_index_types: IndexNode(elasticity_utils.pyx:38:44,
          is_subscript = True,
          result_is_used = True,
          use_managed_ref = True)
      File 'ExprNodes.py', line 4349, in analyse_as_buffer_operation: IndexNode(elasticity_utils.pyx:38:44,
          is_subscript = True,
          result_is_used = True,
          use_managed_ref = True)
      File 'ExprNodes.py', line 4968, in analyse_types: MemoryViewIndexNode(elasticity_utils.pyx:38:44,
          is_memview_index = True,
          memslice_index = True,
          result_is_used = True,
          use_managed_ref = True)
      
      Compiler crash traceback from this point on:
        File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Compiler/ExprNodes.py", line 4968, in analyse_types
          performance_hint(index.pos, "Index should be typed for more efficient access")
      TypeError: performance_hint() missing 1 required positional argument: 'env'
      Compiling python/pumapy/generation/tpms_utils.pyx because it changed.
      Compiling python/pumapy/physics_models/finite_volume/isotropic_conductivity_utils.pyx because it changed.
      Compiling python/pumapy/physics_models/finite_volume/anisotropic_conductivity_utils.pyx because it changed.
      Compiling python/pumapy/physics_models/finite_volume/elasticity_utils.pyx because it changed.
      [1/4] Cythonizing python/pumapy/generation/tpms_utils.pyx
      [2/4] Cythonizing python/pumapy/physics_models/finite_volume/anisotropic_conductivity_utils.pyx
      [3/4] Cythonizing python/pumapy/physics_models/finite_volume/elasticity_utils.pyx
      Traceback (most recent call last):
        File "/home/emek/miniconda/envs/puma/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/emek/miniconda/envs/puma/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/emek/miniconda/envs/puma/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
        File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: python/pumapy/physics_models/finite_volume/elasticity_utils.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by fsemerar** [comment]
Sorry for the long delay in replying, did you try to install it using the usual conda command? 
i.e. `conda create -y --name puma -c conda-forge puma`

**Comment by 10427788** [comment]
Hi, I tried to install the PUMA with updated anaconda 3 version on Ubuntu 18.04 LTS machine with this terminal command "conda create -y --name puma -c conda-forge puma "
At the end of executing that command, it throws some error called failed to find the enviorinment :+1: 
conda create -y --name puma -c conda-forge puma
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source. Please let me know to way to install PUMA on Ubuntu 18.04LTS

**Comment by 10427788** [comment]
> Dear All
> 
> I am building from scratch and after compiling, by installing, I receive this error and it stops. Any idea what to change?
> 
> Starting pumapy installation.
> 
> Processing /home/prog/puma Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [95 lines of output] /tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/prog/puma/python/pumapy/generation/tpms_utils.pyx tree = Parsing.p_module(s, pxd, full_module_name) /tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/prog/puma/python/pumapy/physics_models/finite_volume/anisotropic_conductivity_utils.pyx tree = Parsing.p_module(s, pxd, full_module_name) /tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/prog/puma/python/pumapy/physics_models/finite_volume/elasticity_utils.pyx tree = Parsing.p_module(s, pxd, full_module_name)
> 
> ```
>   Error compiling Cython file:
>   ------------------------------------------------------------
>   ...
>   
>       for i in range(len_x + 2):
>           for j in range(len_y + 2):
>               for k in range(len_z + 2):
>                   if i == 0 or i == len_x + 1 or j == 0 or j == len_y + 1 or k == 0 or k == len_z + 1:
>                       ws_pad[i, j, k] = ws_pad[index_at_pad(i, len_x + 1),
>                                               ^
>   ------------------------------------------------------------
>   
>   python/pumapy/physics_models/finite_volume/elasticity_utils.pyx:38:44: Compiler crash in AnalyseExpressionsTransform
>   
>   ModuleNode.body = StatListNode(elasticity_utils.pyx:1:0)
>   StatListNode.stats[7] = StatListNode(elasticity_utils.pyx:25:0)
>   StatListNode.stats[0] = DefNode(elasticity_utils.pyx:25:0,
>       is_cyfunction = True,
>       modifiers = [...]/0,
>       name = 'pad_domain_cy',
>       np_args_idx = [...]/0,
>       num_required_args = 7,
>       outer_attrs = [...]/2,
>       py_wrapper_required = True,
>       reqd_kw_flags_cname = '0',
>       used = True)
>   File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:27:4)
>   File 'Nodes.py', line 7556, in analyse_expressions: ForInStatNode(elasticity_utils.pyx:34:4)
>   File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:35:8)
>   File 'Nodes.py', line 7556, in analyse_expressions: ForInStatNode(elasticity_utils.pyx:35:8)
>   File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:36:12)
>   File 'Nodes.py', line 7556, in analyse_expressions: ForInStatNode(elasticity_utils.pyx:36:12)
>   File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:37:16)
>   File 'Nodes.py', line 7137, in analyse_expressions: IfStatNode(elasticity_utils.pyx:37:16)
>   File 'Nodes.py', line 7184, in analyse_expressions: IfClauseNode(elasticity_utils.pyx:37:19)
>   File 'Nodes.py', line 397, in analyse_expressions: StatListNode(elasticity_utils.pyx:38:44)
>   File 'Nodes.py', line 6026, in analyse_expressions: SingleAssignmentNode(elasticity_utils.pyx:38:44)
>   File 'Nodes.py', line 6158, in analyse_types: SingleAssignmentNode(elasticity_utils.pyx:38:44)
>   File 'ExprNodes.py', line 4082, in analyse_types: IndexNode(elasticity_utils.pyx:38:44,
>       is_subscript = True,
>       result_is_used = True,
>       use_managed_ref = True)
>   File 'ExprNodes.py', line 4123, in analyse_base_and_index_types: IndexNode(elasticity_utils.pyx:38:44,
>       is_subscript = True,
>       result_is_used = True,
>       use_managed_ref = True)
>   File 'ExprNodes.py', line 4349, in analyse_as_buffer_operation: IndexNode(elasticity_utils.pyx:38:44,
>       is_subscript = True,
>       result_is_used = True,
>       use_managed_ref = True)
>   File 'ExprNodes.py', line 4968, in analyse_types: MemoryViewIndexNode(elasticity_utils.pyx:38:44,
>       is_memview_index = True,
>       memslice_index = True,
>       result_is_used = True,
>       use_managed_ref = True)
>   
>   Compiler crash traceback from this point on:
>     File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Compiler/ExprNodes.py", line 4968, in analyse_types
>       performance_hint(index.pos, "Index should be typed for more efficient access")
>   TypeError: performance_hint() missing 1 required positional argument: 'env'
>   Compiling python/pumapy/generation/tpms_utils.pyx because it changed.
>   Compiling python/pumapy/physics_models/finite_volume/isotropic_conductivity_utils.pyx because it changed.
>   Compiling python/pumapy/physics_models/finite_volume/anisotropic_conductivity_utils.pyx because it changed.
>   Compiling python/pumapy/physics_models/finite_volume/elasticity_utils.pyx because it changed.
>   [1/4] Cythonizing python/pumapy/generation/tpms_utils.pyx
>   [2/4] Cythonizing python/pumapy/physics_models/finite_volume/anisotropic_conductivity_utils.pyx
>   [3/4] Cythonizing python/pumapy/physics_models/finite_volume/elasticity_utils.pyx
>   Traceback (most recent call last):
>     File "/home/emek/miniconda/envs/puma/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>       main()
>     File "/home/emek/miniconda/envs/puma/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "/home/emek/miniconda/envs/puma/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>       return hook(config_settings)
>     File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
>       return self._get_build_requires(config_settings, requirements=['wheel'])
>     File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
>       self.run_setup()
>     File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
>       super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
>     File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
>       exec(code, locals())
>     File "<string>", line 23, in <module>
>     File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
>       cythonize_one(*args)
>     File "/tmp/pip-build-env-xto51ezz/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
>       raise CompileError(None, pyx_file)
>   Cython.Compiler.Errors.CompileError: python/pumapy/physics_models/finite_volume/elasticity_utils.pyx
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.

Hi bilenemek
Did you install the PUMA on UBUNTU by directly compiling source from Github ? . Please let me know

**Comment by 10427788** [comment]
Hi, 

conda install conda-forge/label/broken::puma 
Collecting package metadata (current_repodata.json): / WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                            

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - conda-forge/label/broken::puma -> python[version='2.7.*|3.5.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.12,<3.13.0a0|>=3.5,<3.6.0a0|3.6.*|>=3.13,<3.14.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0
  - conda-forge/label/broken::puma -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.27

**Comment by 10427788** [comment]
Hi, 
I do get the same error while building PUMA source code on Ubuntu 22.04 LTS
Kindly let me know the procedure if you resolved the above mentioned problem. Thanks in advance
