### ISSUE TITLE
PuMA is not Running

### ISSUE THREAD

**Issue by Niluka-Athukorala** [nasa/puma#15]
Dear All,

I am using Windows. I installed PuMA as per the instructions in "Documentation", and then tried to run it. But, it is not running and gives an error as indicated in the below snapshot. I tried this several times after uninstalling PuMa and installing it again. But the same error occurred.

"
pumaGUI : The term 'pumaGUI' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pumaGUI
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pumaGUI:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
"

Could you please help me to overcome this issue? 

Thank you

**Comment by Niluka-Athukorala** [comment]
The issue was solved by activating the "Windows Subsystem for Linux - Wsl2)" which is a feature in Windows 10 and installing "Ubuntu" and "Cmake". Then, Installation of PuMa was done using method 2 (i.e Build from Source) in Linux (Ubuntu). It was not successful in the first attempt. Then, I unregistered the "Ubuntu" and registered it again using Windows power shell. Next, all the steps of installing PuMa were repeated.  Finally, it was successful. PuMa GUI was able to run. 
The first instruction (i.e. to use  Wsl) was given by Mr Joseph. Then, you can find the rest of the resources by searching on the web ( as I did).  I wish to thank Joseph and all the developers. 
NILUKA

**Comment by andtoni** [comment]
Hi Niluka

Thank you for kindly providing your solution. I have followed every step as carefully as possible:
1. Install and run WSL2 in PowerShell, install Ubuntu, install cMake 
2. Install PuMA using method 2

Everything works great and my PuMA successfully installs, and I cant activate the conda environment, however, when I try run 'pumaGUI' it just states "command not found". I would sincerely appreciate any assistance or a more details explanation.
