### ISSUE TITLE
Request for a method to calculate the required memory

### ISSUE THREAD

**Issue by JillianYuan** [nasa/puma#2]
Hi,

Thank you so much for this nice code and clear documentation. I found it very easy to start a simulation with your code.

But sometimes a simulation may take forever because the dataset is too big. I am wondering if it is possible to have a method to compute the required memory before a simulation starts?

Jillian

**Comment by fsemerar** [comment]
Hi Jilian, I have just pushed a new function called estimate_max_memory, which computes a rough estimate of the peak extra memory required by the following functions: anisotropic_conductivity, isotropic_conductivity, tortuosity, elasticity, permeability.

**Comment by JillianYuan** [comment]
Hi Federico, Thank you!
