### ISSUE TITLE
Crash on exit with VTK 8.2.0

### ISSUE THREAD

**Issue by EricAtORS** [nasa/puma#3]
There's a segmentation fault with VTK 8.2.0.

**Comment by EricAtORS** [comment]
The issue seems to be with pyvista.
For some reason, importing it causes a segfault with Dragonfly.
Would it be possible to lazily load it? Like to move the import statements from being a module level import in  `render.py` and in the `isosurface.py` inside the function call?

**Comment by fsemerar** [comment]
Added lazy import of pyvista, currently rebuilding on pypi and conda
