### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by LolloCappo** [nasa/puma#4]
I am having problems during the installation on win10. 
Once typed '**pip install pumapy**' I get  '**No matching distribution found for pumapy**'.
It is probably my bad, but how can I solve it? Thanks in advance.
Lorenzo

**Comment by fsemerar** [comment]
Ciao Lorenzo, thank you for your report, I will look into this issue as soon as I can.  In the meantime to get you going, I'd recommend using the `conda create -y --name puma conda-forge::puma` command, which on Windows is equivalent to `pip install pumapy` and only installs the python package.

**Comment by LolloCappo** [comment]
Ok, I will do this way.
Thank you very much Federico!

**Comment by LolloCappo** [comment]
Ciao Federico,
the **conda create -y --name puma conda-forge::puma** is working. However, I am not able to launch the pumaGUI.
Any suggestion with that?
Thank you in advance

**Comment by fsemerar** [comment]
On windows 10, only the pumapy python package is available (you can find an explanation in the installation section of the README). Since the PuMA GUI was implemented in C++, it is a feature only available on Linux and Mac.
