### ISSUE TITLE
Option to disable the log 

### ISSUE THREAD

**Issue by JillianYuan** [nasa/puma#7]
Hello Federico,

Thanks for adding the option to change the directory of the log file. 
Is it possible to add a flag to allow users to enable/disable the log?

Jillian

**Comment by fsemerar** [comment]
Hi Jilian, 

A quick solution to your problem could be to simply use the tempfile library as:

```
import tempfile
tmp_dir = tempfile.TemporaryDirectory()
puma.settings['log_location'] = tmp_dir.name

# example code that generates logfile
ws = puma.generate_sphere((100, 100, 100), (50, 50, 50), 80)
puma.render_volume(ws)
```

This creates a temporary directory that gets automatically cleaned at the end of the script execution. Let me know if this solves it for you. 

Federico
