### ISSUE TITLE
Compute Elasticity in the 'xy', 'xz', and 'yz' directions

### ISSUE THREAD

**Issue by jamshidk** [nasa/puma#8]
Puma is not able to to evaluate the stiffness in ‘xy’, ‘xz’, and ‘yz’ directions. 

When I run the code for ‘xy’, ‘yz’, and ‘xz’ direction I got this error:

Invalid simulation direction, it can be only ‘x’, ‘y’, ‘z’

I am wondering if you have a solution for this error.

**Comment by fsemerar** [comment]
Thank you for pointing this out, we will be addressing this shortcoming in the upcoming 3.2 release
