### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by AtilMohAmine** [nasa/puma#9]
I have issue when i running `import pumapy` on last version of numpy.

`File "/home/amine/anaconda3/envs/puma/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
`

I think the issue is because of:

- numpy 1.20 [(release notes)](https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations) deprecated numpy.float, numpy.int, and similar aliases, causing them to issue a deprecation warning.

- numpy 1.24 [(release notes)](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations) removed these aliases altogether, causing an error when they are used.

**Comment by joseph-ferguson** [comment]
Thanks for brining this issue to our attention! We will fix this right away.

**Comment by joseph-ferguson** [comment]
We probably won't be able to get this fix pushed to the NASA github until next week. But if any other users are having this issue, they can solve it by doing the following: 

------ If you Installed using the conda-forge installation --------
1. Open a terminal
2. Execute 'conda activate puma'
3. Execute 'conda install numpy=1.23'

-------- If you installed by downloading the software and using the ./installer.sh script -------
1. Open a terminal and navigate to the puma-dev directory
2. Execute 'conda activate puma'
3. Execute 'conda install numpy=1.23'
4. Execute 'conda activate base'
5. Execute './installer.sh'


The puma package should work properly after this

**Comment by joseph-ferguson** [comment]
Changes were reviewed. Installation was tested, and c++ and python unit tests were run. Everything looks great (except one new failing test, which fails independent of this change, and will be fixed separately), so the merge is approved. Federico will execute merge.

Thanks for your help!
